# config file

server:
  host: "0.0.0.0"
  port: 8080
  service-key: "service/lignum/key/master"

consul:
  host: "localhost"
  port: 8500
  sessionTTL: "15s"
  sessionRenewalTTL: "15s"

message:
  initial-size-per-topic: 1000
