# config file

server:
  host: "localhost"
  port: 8080
  service-key: "service/lignum/key/master"

consul:
  host: "localhost"
  port: 8500
  sessionTTL: "15s"
  sessionRenewalTTL: "15s"

message:
  initial-size: 1000
  message-dir: "DataDir"
  message-flush-interval-in-ms: 1000
